# Generated by Django 3.2.4 on 2021-07-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_id_package_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='total',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id_package_2',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lat_final',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lat_initial',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lng_final',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lng_initial',
        ),
        migrations.AddField(
            model_name='delivery',
            name='metro_final',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='metro_init',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_receiver',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
    ]
