# Generated by Django 3.2.4 on 2021-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210708_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='name_receiver',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
    ]
