# Generated by Django 3.2.4 on 2021-07-11 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id_user_B',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to=settings.AUTH_USER_MODEL),
        ),
    ]
