# Generated by Django 3.2.4 on 2021-07-12 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0001_initial'),
        ('delivery', '0006_alter_delivery_id_user_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id_package_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_1', to='package.package'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id_user_B',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport', to=settings.AUTH_USER_MODEL),
        ),
    ]
