# Generated by Django 3.2.4 on 2021-07-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('delivery', '0007_auto_20210712_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id_package_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_1', to='package.package'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
